README.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
추가/변경사항에 대해 작성해주세요.
Issue Number: N/A
=> Update to Develop

highpitch/ContentView.swift
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
추가/변경사항에 대해 작성해주세요.
Issue Number: #5
=> [Test] local branch test #5 Close

highpitch/APIs/ReturnZero/ReturnzeroAPI.swift, highpitch/Managers/KeyChainManager.swift, highpitch/extension/Bundel+extension.swift
ReturnZero Api 서비스를 구현했습니다.
ReturnZero Api 서비스 구현
keychain manager 구현
plist(api key 저장) 참조를 위한 bundle extension 구현
-
-
- resolved : #21
=> [Feat] ReturnZero Api 서비스 구현

highpitch.xcodeproj/project.pbxproj, highpitch/Managers/AudioManager.swift
- 오디오 매니저 객체를 구현하였다
- 오디오 녹음 기능
- documents/HighPitch/Audio 를 기본 경로로 설정
- 오디오 재생,멈춤,중지 기능
- 원하는 시점에서 재생 기능
- 오디오 이름 규칙을 설정할 필요 있음
- resolved : #40
=> [Feat] 오디오 재생 녹음 기능 구현 #40

highpitch.xcodeproj/project.pbxproj, highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift, highpitch/DesignSystem/Components/Common/HPStyledLabel.swift, highpitch/DesignSystem/Components/Common/HPTooltip.swift, highpitch/DesignSystem/Components/Common/HPTopToolbar.swift, highpitch/DesignSystem/Foundation/Colors/Colors.swift, highpitch/DesignSystem/Foundation/Layout/Space.swift, highpitch/Presentation/MainWindow/MainWindowView.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift, highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift, highpitch/Utils/Modifier/LabelModifier.swift
디자인 시스템 코드 작성
- 디자인 시스템 코드 작성
- 공용 컴포넌트 분리
- rawvalue -> 디자인시스템값으로 변환
- 디자인 시스템 코드 샘플 뷰 작성 - 전체 연습 통계 (그래프 제외)
- 비정기적으로 수정 예정입니다.
- resolved : #36
=> [Design] 디자인 시스템 코드 작성

highpitch.xcodeproj/project.pbxproj, highpitch/Managers/AudioManager.swift, highpitch/Models/PersistenceModels/PracticeModel.swift, highpitch/Models/PersistenceModels/ProjectModel.swift, highpitch/Models/PersistenceModels/UtteranceModel.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift, highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
- 메인 뷰와 연습 상세 보기 데이터 연동
- 아직 MenuBarExtraView에서 연습 추가 기능은 구현이 안되었습니다.
- resolved : #이슈번호
=> Feat/#45 메인 뷰와 연습 상세 보기 데이터 연동

highpitch.xcodeproj/project.pbxproj, highpitch/Models/PersistenceModels/UtteranceModel.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
- ScriptView에 데이터 연동되었습니다.
- 로키의 sorted comparable 추가되었습니다.
#47
=> Feature/#47 ScriptView data connected

highpitch.xcodeproj/project.pbxproj, highpitch/APIs/ReturnZero/ReturnzeroAPI.swift, highpitch/Managers/AudioManager.swift, highpitch/Presentation/PlayBar/PlayBar.swift
- 오디오 재생 바 구현 
- 오디오 재생 바 구현
- 오디오 재생 바 디자인 수정 요청했습니다
before :
after : 
- resolved : #49
=> Feat 오디오 재생 바 구현 #49

highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
ScriptView 완료하였습니다.
- ScriptView 완료하였습니다.
- 줄간격 혹은 padding이 정확하지 않습니다.
#47
=> Feature/#47 ScriptView done

highpitch.xcodeproj/project.pbxproj, highpitch/DesignSystem/Foundation/Colors/Colors.swift, highpitch/Managers/PracticeManager.swift, highpitch/Managers/ProjectManager.swift, highpitch/Models/DataModels/FillerWord.swift, highpitch/Models/PersistenceModels/FillerWordModel.swift, highpitch/Models/PersistenceModels/PracticeModel.swift, highpitch/Models/PersistenceModels/PracticeSummaryModel.swift, highpitch/Models/PersistenceModels/SentenceModel.swift, highpitch/Models/PersistenceModels/WordModel.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift, highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
practiceModel 제작 완료하였으며 swiftData와 연동되었습니다.
- Word, Sentence, PracticeSummary에서 필요한 데이터 연산 로직 작성
- swiftData와 연동(thanks to coffee)
- (매우 중요) 기존의 Model과 변동되었기 때문에 반드시 PULL 받기 전 기존의 데이터를 초기화하여야 합니다.
#58
=> Feature/#58 Done with creating PracticeModel

highpitch/Managers/AppleScriptManager.swift, highpitch/Managers/KeynoteManager.swift, highpitch/Managers/PracticeManager.swift, highpitch/Managers/ProjectManager.swift, highpitch/Presentation/MainWindow/MainWindowView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift, highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift, highpitch/Presentation/MenubarExtra/MenubarExtraContent/PracticeResultCell.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift, highpitch/Presentation/MenubarExtra/MenubarExtraView.swift, highpitch/Utils/Modifier/LabelModifier.swift
- ExtraMenubar 기능 작성 및 테스트
- DispatchQueue -> MainActor처리
- 애플 스크립트 수정
- UI 데이터 연동 동작
-
- resolved : #59
=> [Feat] ExtraMenubar 작성

highpitch.xcodeproj/project.pbxproj, highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift, highpitch/DesignSystem/Components/Common/HPStyledLabel.swift, highpitch/DesignSystem/Components/Common/HPTooltip.swift, highpitch/DesignSystem/Foundation/Colors/Colors.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift, highpitch/SecretKey.plist
전체연습 통계 UI 설정
- 전체 연습 통계 색상 및 패딩 조절
- 전체 연습 통계 뷰 데이터 연결
- 차트 다듬는중
#71
=> Feat/#71 전체연습 통계 설정 중

highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift, highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift, highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift, highpitch/Utils/Extension/Date+Extension.swift
- connect data in practiceTabitem View
- chart UI in statisticTabitem View
#71 
- resolved : #이슈번호
=> [Feat] #71 chart UI 및 데이터 연동

highpitch/Presentation/MainWindow/MainWindowView.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
- 연습 탭 체크박스 뷰 그리기
-
- resolved : #60
=> [Design] 연습 탭 체크박스 뷰 그리기

highpitch.xcodeproj/project.pbxproj, highpitch/APIs/ReturnZero/ReturnzeroAPIV2.swift
ReturnzeroApiV2 구현
- ReturnzeroApiV2 구현
-
- resolved : #77
=> [Feat] ReturnzeroApiV2 구현 #77

highpitch/Managers/NotificationManager.swift, highpitch/Presentation/MainWindow/MainWindowView.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
LocalNotification으로 뷰 이동 로직 구현
- NotificationCenter 연결
-
- resolved : #88
=> [Feat] LocalNotification으로 뷰 이동 로직 구현 #88

highpitch/Presentation/Settings/SettingsView.swift
- SettingView 틀 구성
- SettingView 틀 구성
- resolved : #81
=> [Feat] SettingView 틀 구성

highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
- 아무 말도 하지 않는 경우 연습을 저장하지 않습니다.
- usagePercentageView index 조회 error control
=> [Fix] 단어 없는 연습 저장 안하기

README.md
- README.md 내 Member 업데이트
- 페이지 방문 수 체크하는거 해당 페이지로 설정
- 
- resolved : #이슈번호
=> [Docs] README.md 내 Member 업데이트

highpitch.xcodeproj/project.pbxproj, highpitch/App/HighPitchApp.swift, highpitch/Managers/PracticeManager.swift, highpitch/Managers/ProjectManager.swift, highpitch/Models/PersistenceModels/PracticeSummaryModel.swift, highpitch/Models/PersistenceModels/SentenceModel.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift, highpitch/Presentation/MainWindow/ProjectView/StatisticTabGraph.swift, highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
- projectManager 내 practices 및 current 삭제
- SentenceModel, SummaryModel 변수 수정
- PracticeChart 내 Model 바꾼 부분에 해당하는 부분 수정
- StatisticTabItem 내 조건문 통합 및 graph 분리 작업
- Model이 변경되었으므로 데이터 삭제 부탁드립니다.
#95
=> Refactor/#95 ProjectManager 및 StatisticTabItem refactor

highpitch/Managers/MediaManager.swift, highpitch/Presentation/MainWindow/MainWindowView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
오디오 뷰 로직 수정하였습니다.
- 오디오 뷰 타이머 멈추면 끄기
- 패스트 레인 뷰 로직 수정
-
- resolved : #95
=> [Fix] 오디오 뷰 로직 수정  #95

highpitch/App/HighPitchApp.swift, highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift, highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
- MenubarExtraView에 있는 selectedProject, selectedKeynote를 한단계 위의 View인 HighpitchApp로 옮김.
- HighpitchApp에서 HotKey 적용.
-
- resolved : #108
=> [Refactor] 앱 실행시 Keyboard Shortcut(Hotkey) 적용

highpitch.xcodeproj/project.pbxproj, highpitch/Presentation/Settings/FeedbackSettingView.swift, highpitch/Presentation/Settings/GeneralSettingView.swift, highpitch/Presentation/Settings/SettingsView.swift
- 세팅 뷰 구현 
- 일반 세팅 뷰 구현
- 피드백 세팅 뷰 구현
-
- resolved : #110
=> [Feat] 세팅 뷰 구현 #110

highpitch/Managers/MediaManager.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
스크립트 play at 즉시 적용
- 오디오 매니저 타이머 중복 오류 제거 
-
- resolved : #110
=> [Fix] 스크립트 play at 즉시 적용 #110

highpitch/App/HighPitchApp.swift, highpitch/Managers/PracticeManager.swift, highpitch/Models/PersistenceModels/PracticeSummaryModel.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
- speechAverage chart 변경
- Model 변경
- 빠른, 느린 문장 선택 로직 변경
- fastSentReplay 변경
- model이 변경되었습니다.
=> Refactor/#95 speechAverage chart 및 fastSentReplay

highpitch/Managers/MediaManager.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift, highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
빠르게 말한 구간 오디오 싱크 수정했습니다
- 빠르게 말한 구간 오디오 싱크
- 오디오 컨트롤러 뷰 currentTime 싱크 안맞는 오류 수정
-
- resolved : #119
=> [Fix] 빠르게 말한 구간 오디오 싱크 수정 #119

highpitch/App/HighPitchApp.swift, highpitch/App/Info.plist, highpitch/DesignSystem/Components/Common/HPTopToolbar.swift, highpitch/Managers/ProjectManager.swift, highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
배포 버전 빌드
-
-
- resolved : #125
=> [Chore] 배포 버전 빌드
